/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 car.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Car (props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/src/assets/car.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube" position={[-2.27, 0.92, -1.48]} scale={[0.43, 0.42, 0.42]}>
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.chassis} />
          <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.headlight} />
          <mesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials.backlight} />
          <mesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials.tire} />
          <mesh name="Cube_5" geometry={nodes.Cube_5.geometry} material={materials.spikes} />
          <mesh name="Cube_6" geometry={nodes.Cube_6.geometry} material={materials.windshield} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car.gltf')
