/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Map.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('src/assets/Map.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.trafficlight.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light3.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light004.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.trafficlight1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.trafficlight2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Floor4.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Floor.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bed.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bushes3.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bed_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bushes3_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.House.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bench1.geometry} material={materials['World ap']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.House_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light3_1.geometry} material={materials['World ap']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light2_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light1_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Floor4_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Floor_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree47.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree3.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree4.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bench.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Muff1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Muff.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light3_2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light2_2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light1_2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light_2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light4.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light5.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Floor4_2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Floor_2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree47_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree3_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree2_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree1_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Firtree4_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bench_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Behch.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.House_2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Shop.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Trash.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Trash_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light3_3.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light2_3.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Light_3.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Floor4_3.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Floor_3.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bed_2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bushes15.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bushes2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bushes.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Tree1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Tree2.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Tree3.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bed_3.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bushes15_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bushes2_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Bushes_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Tree1_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Tree2_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Tree3_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ROAD.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.trafficlight_1.geometry} material={materials['World ap']} position={[-603.58, 340.88, 311.09]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.trafficlight1_1.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.trafficlight2_1.geometry} material={materials['World ap']} position={[-984.37, 340.88, -9.03]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ROADLines12.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Floor_4.geometry} material={materials['World ap']} position={[0, 340.88, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Map.gltf')
